### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Daerphen** [revilheart/Scripts#1]
The script is not yet working for Safari Browsers. This is due to a bug in the Tampermonkey implementation of the Safari Plugin. Tamper monkey on Safari does not load external scripts with @require. 
I have no idea how to manage that. Maybe by adding something like this to your code
$('head').append('<script src="...path/to/script"/>')

**Comment by revilheart** [comment]
I think there's something bigger going on, because I can't get the script to run at all here, at least in the latest version that was made for Windows. I can't test the real latest version since I don't have a Mac.

**Comment by Daerphen** [comment]
Once you fixed it for Windows and commit your changes I can test it on my Mac

**Comment by revilheart** [comment]
I wasn't able to fix it while maintaining the functions in separate files, so I decided to create a minified version for the script, with everything in one file: https://github.com/revilheart/Scripts/blob/master/rhBLAEO/rhBLAEO.Minified.user.js It should be working now, but let me know if there are any issues.

**Comment by Daerphen** [comment]
Yeah, there is an issue. Apparently there is a Bug with Safari, the Object window.location does not get populated. Guess I will just use a different Browser. Only using Mac for work anyway.

**Comment by revilheart** [comment]
Yeah, I've read about some issues that Tampermonkey has with Safari, so I guess there's nothing I can do about it. Thanks for letting me know, I've deleted the minified version.
